
################数据库环境配置################

database:
  jdbcUrl: jdbc:mysql://116.62.166.68:3306/aion_login_server?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
  driver: com.mysql.cj.jdbc.Driver
  username: root
  password: 123456

################网络参数配置################

login-server:
  network:
    client:
      port: 2106
      boss-thread: 1
      worker-thread: 3
      buffer-size: 8196
    main-server:
      port: 14513
      thread: 2
      pingpong-check: true
      buffer-size: 8196

################日志文件配置################
logging:
  config: config/logback/logback-dev.xml